### ISSUE TITLE
Condiciones de privacidad en inglés y español

### ISSUE THREAD

**Issue by laramaktub** [laramaktub/covid19#26]
Dos pdf distintos para inglés y para español.  Cuando tengamos la versión en inglés enlazamos al pdf inglés.

**Comment by ghost** [comment]
PREFERIBLE QUE AL CLICKAR EN "TÉRMINOS Y CONDICIONES" SE VEA EL PDF SIN OPCIÓN A DESCARGA, MÁS QUE QUE TE REDIRECCIONE A DRIVE DONDE ESTA COLGADO EL PDF.

PDF (ESPAÑOL): https://drive.google.com/file/d/15F7yiFtvUZLpIxU1s6TXd_Ni1K3adqYL/view?usp=sharing

PDF (INGLÉS): https://drive.google.com/file/d/1gEsCtx6EUXbjT1w7c7vfHKh39NTRIFWQ/view?usp=sharing
