### ISSUE TITLE
CAMBIOS

### ISSUE THREAD

**Issue by ghost** [laramaktub/covid19#5]
Update cambios:

URGENTISIMO:
- Puedes darle a continuar sin escoger especialidad
- El sexo sale en inglés
- Adaptar botones de seleccionar diagnóstico
- En la interfaz de seleccionar la especialidad, cambiar texto a “Bienvenido a COVID-19 training”
- Cambiar enlace términos a pdf (tienes el enlace en el mail)
- Puedes acceder a cualquier interfaz sin logearte te metiendo la url
- Agradecimientos en otro cuadrado debajo de log in. 

URGENTE
- Adaptar versión móvil
- Interfaz de portada

MENOS URGENTE
- Adaptar versión inglés

**Comment by laramaktub** [comment]
Gracias Pablo!

Respecto a "Puedes darle a continuar sin escoger especialidad" deberíamos entonces, si quieres hacerlo obligatorio, poner Otros. Por si alguien se conecta y no tiene nada que ver con esos perfiles.

**Comment by ghost** [comment]
Gran idea!

**Comment by ghost** [comment]
Tenemos una nueva tarea, la pongo por aquí para Fernando y Pedro, Lara está al tanto. Que os parece introducir agradecimientos y dedicar la app al personal lucha contra el COVID-19 (idea de nuestro jefe de servicio) ?. El hospital promocionara la app. Por otro lado, también agradecimientos a Lara, David, Fernando, Pedro, y CAFE asociados por vuestro trabajo altruista!

**Comment by Pablomfm** [comment]
Update cambios:

URGENTISIMO:
- Puedes darle a continuar sin escoger especialidad
- El sexo sale en inglés
- Adaptar botones de seleccionar diagnóstico
- En la interfaz de seleccionar la especialidad, cambiar texto a “Bienvenido a COVID-19 training”
- Cambiar enlace términos a pdf (tienes el enlace en el mail)
- Puedes acceder a cualquier interfaz sin logearte te metiendo la url
- Agradecimientos en otro cuadrado debajo de log in. 

URGENTE
- Adaptar versión móvil
- Interfaz de portada

MENOS URGENTE
- Adaptar versión inglés

**Comment by Pablomfm** [comment]
- Puedes darle a continuar sin escoger especialidad

**Comment by Pablomfm** [comment]
El sexo sale en inglés

**Comment by Pablomfm** [comment]
Adaptar botones de seleccionar diagnóstico

**Comment by Pablomfm** [comment]
Cambiar enlace términos a pdf (tienes el enlace en el mail)

**Comment by Pablomfm** [comment]
Puedes acceder a cualquier interfaz sin logearte te metiendo la url

**Comment by ghost** [comment]
IMPORTANTE: en la primera interfaz debajo del cuadrado de log in otro cuadrado con agradecimientos con el texto y diseño que enviaré a Pedro al mail. De momento estamos en ello.

**Comment by Pablomfm** [comment]
Adaptar versión móvil

**Comment by ghost** [comment]
Interfaz de portada

**Comment by ghost** [comment]
Adaptar versión inglés

**Comment by Pedrosolisg** [comment]
> * Puedes darle a continuar sin escoger especialidad

Esto no pasa pablin. El usuario si no esta logeado necesita iniciar sesion antes de acceder a cualquier pestania que no sea la de login

**Comment by pedrosolisgarcia** [comment]
> Puedes acceder a cualquier interfaz sin logearte te metiendo la url

Esto no pasa pablin. El usuario si no esta logeado necesita iniciar sesion antes de acceder a cualquier pestania que no sea la de login
