### ISSUE TITLE
You can proceed to Training screen without selecting speciality

### ISSUE THREAD

**Issue by pedrosolisgarcia** [laramaktub/covid19#6]
**Steps to reproduce:**

1. Go to _logged_ screen.

2. Don't select any speciality.

3. Click on the _Continuar_ button.

**Expected Result:**
An error message pops up, asking you to select speciality.

**Actual Result:**
The _training_ screen shows up.

**Comment by laramaktub** [comment]
Deberiamos hacer que si ya lo ha metido una vez, no tenga que volver a meterlo. Le echo un vistazo.

**Comment by pedrosolisgarcia** [comment]
> Deberiamos hacer que si ya lo ha metido una vez, no tenga que volver a meterlo. Le echo un vistazo.

Se puede! Pero no se deberia almacenar dicha informacion en el Frontend. Backend ha de tener un record del usuario con la especialidad si este la ha seleccionado. En dicho caso, en frontend mostrariamos el select con la especialidad preseleccionada.
Si veis bien ir mas adelante con esto, deberiamos hacer un ticket improvement, aunque de momento no es de caracter urgente.
